# Generated by Django 5.0.3 on 2024-03-21 05:49

from django.db import migrations


def apply_migration(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Group.objects.bulk_create(
        [
            Group(name="AppViewer"),
            Group(name="AppCreator"),
            Group(name="AppEditor"),
            Group(name="AppApprover"),
        ]
    )


def revert_migration(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Group.objects.filter(
        name__in=[
            "AppViewer",
            "AppCreator",
            "AppEditor",
            "AppApprover",
        ]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0001_initial"),
    ]

    operations = [migrations.RunPython(apply_migration, revert_migration)]
